// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAtlasSchemaRevision = "atlas_schema_revisions"

// AtlasSchemaRevision mapped from table <atlas_schema_revisions>
type AtlasSchemaRevision struct {
	Version         string    `gorm:"column:version;type:character varying;primaryKey" json:"version"`
	Description     string    `gorm:"column:description;type:character varying;not null" json:"description"`
	Type            int64     `gorm:"column:type;type:bigint;not null;default:2" json:"type"`
	Applied         int64     `gorm:"column:applied;type:bigint;not null" json:"applied"`
	Total           int64     `gorm:"column:total;type:bigint;not null" json:"total"`
	ExecutedAt      time.Time `gorm:"column:executed_at;type:timestamp with time zone;not null" json:"executed_at"`
	ExecutionTime   int64     `gorm:"column:execution_time;type:bigint;not null" json:"execution_time"`
	Error           *string   `gorm:"column:error;type:text" json:"error"`
	ErrorStmt       *string   `gorm:"column:error_stmt;type:text" json:"error_stmt"`
	Hash            string    `gorm:"column:hash;type:character varying;not null" json:"hash"`
	PartialHashes   *string   `gorm:"column:partial_hashes;type:jsonb" json:"partial_hashes"`
	OperatorVersion string    `gorm:"column:operator_version;type:character varying;not null" json:"operator_version"`
}

// TableName AtlasSchemaRevision's table name
func (*AtlasSchemaRevision) TableName() string {
	return TableNameAtlasSchemaRevision
}
