name: Auto Assign Assignee to PR

on:
  pull_request:
    types: [opened, reopened]

permissions: {}

jobs:
  assign:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      pull-requests: write # pr edit by gh
      repository-projects: read # pr edit by gh

    steps:
      - run: gh pr edit "$NUMBER" --add-assignee "$ASSIGNEE"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          ASSIGNEE: ${{ github.event.pull_request.user.login }}
        if:
          ${{ toJSON(github.event.pull_request.assignees) == '[]' &&
          github.event.pull_request.user.login != 'renovate[bot]' }}
